export const constants = {
    CREATE_REMINDER:"CREATE_REMINDER",
    UPDATE_REMINDER:"UPDATE_REMINDER",
    DELETE_REMINDER:"DELETE_REMINDER",
    CLEAR_ALL_REMINDERS:"CLEAR_ALL_REMINDERS",
    CANCEL_SCHEDULED_REMINDER:"CANCEL_SCHEDULED_REMINDER",
    SCHEDULE_REMINDER:"SCHEDULE_REMINDER",
    TOGGLE_DARK:"TOGGLE_DARK"
}